FROM apache

LABEL maintainer=christian.wuensch@ukmuenster.de
LABEL version=1.0

WORKDIR ~
COPY www /var/www/html

# Database configuration
RUN echo "<?php" > /var/www/html/inc/constants.inc.php
RUN echo "    define('DB_HOST', 'localhost');" >> /var/www/html/inc/constants.inc.php
RUN echo "    define('DB_USER', 'amlvaran');" >> /var/www/html/inc/constants.inc.php
RUN echo "    define('DB_PASS', '');" >> /var/www/html/inc/constants.inc.php
RUN echo "    define('DB_NAME', 'amlvaran');" >> /var/www/html/inc/constants.inc.php
RUN echo "?>" >> /var/www/html/inc/constants.inc.php
