FROM php:5-apache

ENV MYSQL_HOST=127.0.0.1
ENV MYSQL_USER=amlvaran
ENV MYSQL_PASSWORD=123456 
ENV MYSQL_DATABASE=amlvaran 

ENV APACHE_DOCUMENT_ROOT /var/www
ENV APACHE_RUN_USER wwwdata
ENV APACHE_RUN_GROUP wwwdata

RUN apt-get -q update && apt-get install -y \
  libfontconfig1 libxrender1 libxext6
RUN docker-php-ext-install pdo pdo_mysql

RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

RUN echo "file_uploads = On\n" \
         "memory_limit = 8G\n" \
         "upload_max_filesize = 8G\n" \
         "post_max_size = 8G\n" \
         "max_execution_time = 600\n" \
         > /usr/local/etc/php/conf.d/uploads.ini

#COPY www/ /var/www/
#RUN chmod a+x /var/www/inc/wkhtmltox/bin/wkhtmltopdf

# Database configuration
#RUN echo "<?php" > /var/www/inc/constants.inc.php
#RUN echo "    define('DB_HOST', '${MYSQL_HOST}');" >> /var/www/inc/constants.inc.php
#RUN echo "    define('DB_USER', '${MYSQL_USER}');" >> /var/www/inc/constants.inc.php
#RUN echo "    define('DB_PASS', '${MYSQL_PASSWORD}');" >> /var/www/inc/constants.inc.php
#RUN echo "    define('DB_NAME', '${MYSQL_DATABASE}');" >> /var/www/inc/constants.inc.php
#RUN echo "?>" >> /var/www/inc/constants.inc.php
